services:
  db:
    image: mysql:8.4.3
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: movieservice
      MYSQL_USER: homework
      MYSQL_PASSWORD: homeworkpass
    ports:
      - "3306:3306"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  app:
    image: movieservice-app:latest  # Use the image you created
    depends_on:
      - db
      - redis
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - MYSQL_URL=jdbc:mysql://db:3306/movieservice
      - MYSQL_USER=homework
      - MYSQL_PASSWORD=homeworkpass
      - OMDB_APIKEY=
      - TMDB_APIKEY=

