server:
  port: 8080
logging:
  level:
    org.springframework.jdbc.datasource.DriverManagerDataSource: DEBUG
spring:
  application:
    name: movieservice
    OMDB:
      apikey: ${OMDB_APIKEY}
    TMDB:
      apikey: ${TMDB_APIKEY}
  datasource:
    url: ${MYSQL_URL:jdbc:mysql://192.168.1.3:9906/movieservice}
    username: ${MYSQL_USER:homework}
    password: ${MYSQL_PASSWORD:homeworkpass}
    driver-class-name: com.mysql.cj.jdbc.Driver
    tomcat:
      max-wait: 30000
      max-active: 10
      max-idle: 5
      min-idle: 5
      validation-query: SELECT 1
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        show_sql: false
        default_schema: movieservice
  data:
    redis:
      host: localhost
      port: 6379