CREATE TABLE IF NOT EXISTS MOVIE_DATA_REQUEST
(
ID BIGINT NOT NULL AUTO_INCREMENT,
MOVIE_API VARCHAR(50) NOT NULL,
MOVIE_TITLE VARCHAR(500) NOT NULL,
REQUEST_TIME DATETIME NOT NULL,
PRIMARY KEY (ID)
);
